### ISSUE TITLE
스타일 수정

### ISSUE THREAD

**Issue by alreadynyeong** [BETTER-iTER/Web#125]
## 설명
> description

## To-do
- [x] 전문가 뱃지 수정
- [x] 홈 타이틀 이모지 추가
- [x] 스펙이 없는 경우 리스트 수정
- [x] 기타 수정사항
