### ISSUE TITLE
검색 기능 수정

### ISSUE THREAD

**Issue by alreadynyeong** [BETTER-iTER/Web#140]
## 설명
> 검색기능 수정
쿼리스트링으로 바꾸기

## To-do
- [ ] 홈, 검색 초기화면에서의 선택으로 인한 결과 반환
- [ ] 키워드 검색과 중첩되지 않게 처리
- [ ] 카테고리 검색시 필터부분 숨김
- [ ] 뒤로가기 처리
