### ISSUE TITLE
회원가입 화면 구현

### ISSUE THREAD

**Issue by alreadynyeong** [BETTER-iTER/Web#17]
## 설명
> 추가 정보 입력 전 회원가입 화면 구현

## To-do
- [x] 이메일/비밀번호 형식 체크=
- [x] 약관 동의 체크
- [ ] 버튼 활성화 조건 설정
