### ISSUE TITLE
일반 회원가입 API 연동

### ISSUE THREAD

**Issue by alreadynyeong** [BETTER-iTER/Web#29]
## 설명
> 일반 회원가입 API 연동

## To-do
- [ ] 이메일 인증요청 API
- [ ] 이메일 인증 코드 검증 
- [ ] 닉네임 중복 체크
- [ ] 일반 회원가입 API
- [ ] 기타 필요한 작업
