### ISSUE TITLE
검색화면 구현

### ISSUE THREAD

**Issue by alreadynyeong** [BETTER-iTER/Web#43]
## 설명
> 검색 관련 화면 구현

## To-do
- [x] 검색중- 카테고리
- [x] 검색중- 최근 검색어
- [x] 검색중- 추천 검색어
- [x] 검색결과
- [x] 하단 카테고리 및 정렬
